### ISSUE TITLE
Chore update fails

### ISSUE THREAD

**Issue by wormiedk** [bmcclure/ha-chore-helper#63]
## System Information

version | core-2024.8.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.46-haos
arch | x86_64
timezone | Europe/Copenhagen
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4988
Installed Version | 2.0.0
Stage | running
Available Repositories | 1466
Downloaded Repositories | 63

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 1 January 2018 at 01:00
relayer_connected | false
relayer_region | null
remote_enabled | true
remote_connected | false
alexa_enabled | false
google_enabled | false
remote_server | null
certificate_status | null
instance_id | 704fe0627b7f423c845bbd57075b6dc6
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.1
-- | --
update_channel | beta
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 30.8 GB
disk_used | 20.4 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | kvm
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Mosquitto broker (6.4.1), RTSP Simple Server Add-on (v0.17.6), Advanced SSH & Web Terminal (18.0.0), File editor (5.8.0), Matter Server (6.4.1), ESPHome (2024.8.1), Piper (1.5.2), eufy-security-ws (1.9.0), Firefox (1.2.0), Dropbox Sync (1.3.0), Tailscale (0.21.0), DbStats (0.5.8), Music Assistant Server (2.2.2)

</details>

<details><summary>Dashboards</summary>

dashboards | 4
-- | --
resources | 36
views | 26
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 24 August 2024 at 06:26
-- | --
current_recorder_run | 28 August 2024 at 10:54
estimated_db_size | 2138.48 MiB
database_engine | mysql
database_version | 10.9.5

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bmcclure/ha-chore-helper/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Error in the log when booting/updating chore

Settings for chore:
![image](https://github.com/user-attachments/assets/2ea66578-3335-4df5-a22d-ab6957e6b762)
![image](https://github.com/user-attachments/assets/87f6e624-e466-46c4-b9c7-9a4f7615b663)

### Reproduction steps

1. Create chore
2. Possibly add and try to remove an extra due date

### Debug logs

```Text
Debug log to long. Here is everything relating to this integration

2024-08-28 10:17:24.621 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk vandhaner) Calling update
2024-08-28 10:17:25.098 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk vandhaner) Dates loaded, firing a chore_helper_loaded event
2024-08-28 10:17:25.098 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event chore_helper_loaded[L]: entity_id=sensor.afkalk_vandhaner, due_dates=['2024-11-02']>
2024-08-28 10:17:25.098 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk vandhaner) Looking for next chore date
2024-08-28 10:17:25.098 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk vandhaner) next_due_date (2024-11-02), today (2024-08-28)
2024-08-28 10:17:25.098 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk vandhaner) Found next chore date: 2024-11-02, that is in 66 days
2024-08-28 10:17:25.098 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.afkalk_vandhaner, old_state=<state sensor.afkalk_vandhaner=66; last_completed=None, last_updated=None, overdue=False, overdue_days=0, next_due_date=2024-11-02, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:faucet, friendly_name=Afkalk vandhaner @ 2024-08-28T10:16:54.614251+02:00>, new_state=<state sensor.afkalk_vandhaner=66; last_completed=None, last_updated=2024-08-28T10:17:25.098673+02:00, overdue=False, overdue_days=0, next_due_date=2024-11-02, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:faucet, friendly_name=Afkalk vandhaner @ 2024-08-28T10:16:54.614251+02:00>>
2024-08-28 10:17:25.099 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event chore_helper_loaded[L]: entity_id=sensor.afkalk_vandhaner, due_dates=['2024-11-02']>
2024-08-28 10:17:25.100 DEBUG (MainThread) [paho.mqtt.client] Received PUBLISH (d0, q0, r0, m0), 'stat/rpi1/brightness', ...  (3 bytes)
2024-08-28 10:17:25.100 DEBUG (MainThread) [homeassistant.components.mqtt.client] Received message on stat/rpi1/brightness (qos=0): b'100'
2024-08-28 10:17:25.101 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk kaffemaskine og elkedel) Calling update
2024-08-28 10:17:25.101 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk kaffemaskine og elkedel) Dates loaded, firing a chore_helper_loaded event
2024-08-28 10:17:25.101 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event chore_helper_loaded[L]: entity_id=sensor.afkalk_kaffemaskine_og_elkedel, due_dates=['2024-10-05', '2024-12-07', '2025-02-01', '2025-04-05', '2025-06-07', '2025-08-02', '2025-10-04', '2025-12-06', '2026-02-07', '2026-04-04', '2026-06-06']>
2024-08-28 10:17:25.101 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk kaffemaskine og elkedel) Looking for next chore date
2024-08-28 10:17:25.101 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk kaffemaskine og elkedel) next_due_date (2024-10-05), today (2024-08-28)
2024-08-28 10:17:25.101 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk kaffemaskine og elkedel) Found next chore date: 2024-10-05, that is in 38 days
2024-08-28 10:17:25.102 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.afkalk_kaffemaskine_og_elkedel, old_state=<state sensor.afkalk_kaffemaskine_og_elkedel=38; last_completed=None, last_updated=None, overdue=False, overdue_days=0, next_due_date=2024-10-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:coffee-maker-outline, friendly_name=Afkalk kaffemaskine og elkedel @ 2024-08-28T10:16:54.639861+02:00>, new_state=<state sensor.afkalk_kaffemaskine_og_elkedel=38; last_completed=None, last_updated=2024-08-28T10:17:25.101916+02:00, overdue=False, overdue_days=0, next_due_date=2024-10-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:coffee-maker-outline, friendly_name=Afkalk kaffemaskine og elkedel @ 2024-08-28T10:16:54.639861+02:00>>
2024-08-28 10:17:25.102 DEBUG (MainThread) [custom_components.chore_helper] (Udskift nødbeholdningsvand) Calling update
2024-08-28 10:17:25.102 DEBUG (MainThread) [custom_components.chore_helper] (Udskift nødbeholdningsvand) Dates loaded, firing a chore_helper_loaded event
2024-08-28 10:17:25.102 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event chore_helper_loaded[L]: entity_id=sensor.udskift_nodbeholdningsvand, due_dates=['2025-07-05', '2026-07-05', '2027-07-05', '2028-07-05', '2029-07-05', '2030-07-05', '2031-07-05', '2032-07-05', '2033-07-05', '2034-07-05', '2035-07-05']>
2024-08-28 10:17:25.102 DEBUG (MainThread) [custom_components.chore_helper] (Udskift nødbeholdningsvand) Looking for next chore date
2024-08-28 10:17:25.102 DEBUG (MainThread) [custom_components.chore_helper] (Udskift nødbeholdningsvand) next_due_date (2025-07-05), today (2024-08-28)
2024-08-28 10:17:25.102 DEBUG (MainThread) [custom_components.chore_helper] (Udskift nødbeholdningsvand) Found next chore date: 2025-07-05, that is in 311 days
2024-08-28 10:17:25.103 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.udskift_nodbeholdningsvand, old_state=<state sensor.udskift_nodbeholdningsvand=311; last_completed=None, last_updated=None, overdue=False, overdue_days=0, next_due_date=2025-07-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:water-outline, friendly_name=Udskift nødbeholdningsvand @ 2024-08-28T10:16:54.640763+02:00>, new_state=<state sensor.udskift_nodbeholdningsvand=311; last_completed=None, last_updated=2024-08-28T10:17:25.102882+02:00, overdue=False, overdue_days=0, next_due_date=2025-07-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:water-outline, friendly_name=Udskift nødbeholdningsvand @ 2024-08-28T10:16:54.640763+02:00>>
2024-08-28 10:17:25.103 DEBUG (MainThread) [custom_components.chore_helper] (Rens filter Duka stue) Calling update
2024-08-28 10:17:25.114 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event state_changed[L]: entity_id=sensor.afkalk_vandhaner, old_state=<state sensor.afkalk_vandhaner=66; last_completed=None, last_updated=None, overdue=False, overdue_days=0, next_due_date=2024-11-02, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:faucet, friendly_name=Afkalk vandhaner @ 2024-08-28T10:16:54.614251+02:00>, new_state=<state sensor.afkalk_vandhaner=66; last_completed=None, last_updated=2024-08-28T10:17:25.098673+02:00, overdue=False, overdue_days=0, next_due_date=2024-11-02, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:faucet, friendly_name=Afkalk vandhaner @ 2024-08-28T10:16:54.614251+02:00>>
2024-08-28 10:17:25.120 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event chore_helper_loaded[L]: entity_id=sensor.afkalk_kaffemaskine_og_elkedel, due_dates=['2024-10-05', '2024-12-07', '2025-02-01', '2025-04-05', '2025-06-07', '2025-08-02', '2025-10-04', '2025-12-06', '2026-02-07', '2026-04-04', '2026-06-06']>
2024-08-28 10:17:25.127 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event state_changed[L]: entity_id=sensor.afkalk_kaffemaskine_og_elkedel, old_state=<state sensor.afkalk_kaffemaskine_og_elkedel=38; last_completed=None, last_updated=None, overdue=False, overdue_days=0, next_due_date=2024-10-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:coffee-maker-outline, friendly_name=Afkalk kaffemaskine og elkedel @ 2024-08-28T10:16:54.639861+02:00>, new_state=<state sensor.afkalk_kaffemaskine_og_elkedel=38; last_completed=None, last_updated=2024-08-28T10:17:25.101916+02:00, overdue=False, overdue_days=0, next_due_date=2024-10-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:coffee-maker-outline, friendly_name=Afkalk kaffemaskine og elkedel @ 2024-08-28T10:16:54.639861+02:00>>
2024-08-28 10:17:25.134 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event chore_helper_loaded[L]: entity_id=sensor.udskift_nodbeholdningsvand, due_dates=['2025-07-05', '2026-07-05', '2027-07-05', '2028-07-05', '2029-07-05', '2030-07-05', '2031-07-05', '2032-07-05', '2033-07-05', '2034-07-05', '2035-07-05']>
2024-08-28 10:17:25.140 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event state_changed[L]: entity_id=sensor.udskift_nodbeholdningsvand, old_state=<state sensor.udskift_nodbeholdningsvand=311; last_completed=None, last_updated=None, overdue=False, overdue_days=0, next_due_date=2025-07-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:water-outline, friendly_name=Udskift nødbeholdningsvand @ 2024-08-28T10:16:54.640763+02:00>, new_state=<state sensor.udskift_nodbeholdningsvand=311; last_completed=None, last_updated=2024-08-28T10:17:25.102882+02:00, overdue=False, overdue_days=0, next_due_date=2025-07-05, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:water-outline, friendly_name=Udskift nødbeholdningsvand @ 2024-08-28T10:16:54.640763+02:00>>
2024-08-28 10:17:26.078 DEBUG (MainThread) [custom_components.chore_helper] (Rens filter Duka stue) Dates loaded, firing a chore_helper_loaded event
2024-08-28 10:17:26.079 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event chore_helper_loaded[L]: entity_id=sensor.rens_filter_duka_stue, due_dates=[]>
2024-08-28 10:17:26.079 DEBUG (MainThread) [custom_components.chore_helper] (Rens filter Duka stue) Looking for next chore date
2024-08-28 10:17:26.079 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=sensor.rens_filter_duka_stue, old_state=<state sensor.rens_filter_duka_stue=unknown; last_completed=None, last_updated=None, overdue=False, overdue_days=None, next_due_date=None, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:fan, friendly_name=Rens filter Duka stue @ 2024-08-28T10:16:54.641572+02:00>, new_state=<state sensor.rens_filter_duka_stue=unknown; last_completed=None, last_updated=2024-08-28T10:17:26.079334+02:00, overdue=False, overdue_days=None, next_due_date=None, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:fan, friendly_name=Rens filter Duka stue @ 2024-08-28T10:16:54.641572+02:00>>
2024-08-28 10:17:26.079 DEBUG (MainThread) [custom_components.chore_helper] (Afkalk vaskemaskine) Calling update
2024-08-28 10:17:26.080 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event chore_helper_loaded[L]: entity_id=sensor.rens_filter_duka_stue, due_dates=[]>
2024-08-28 10:17:26.082 DEBUG (Recorder) [homeassistant.components.recorder.core] Processing task: <Event state_changed[L]: entity_id=sensor.rens_filter_duka_stue, old_state=<state sensor.rens_filter_duka_stue=unknown; last_completed=None, last_updated=None, overdue=False, overdue_days=None, next_due_date=None, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:fan, friendly_name=Rens filter Duka stue @ 2024-08-28T10:16:54.641572+02:00>, new_state=<state sensor.rens_filter_duka_stue=unknown; last_completed=None, last_updated=2024-08-28T10:17:26.079334+02:00, overdue=False, overdue_days=None, next_due_date=None, offset_dates=None, add_dates=None, remove_dates=None, unit_of_measurement=days, device_class=chore_helper__schedule, icon=mdi:fan, friendly_name=Rens filter Duka stue @ 2024-08-28T10:16:54.641572+02:00>>
2024-08-28 10:17:26.080 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.afkalk_vaskemaskine fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 942, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1300, in async_device_update
    await self.async_update()
  File "/config/custom_components/chore_helper/chore.py", line 448, in async_update
    await self._async_load_due_dates()
  File "/config/custom_components/chore_helper/chore.py", line 361, in _async_load_due_dates
    for chore_date in self.chore_schedule():
  File "/config/custom_components/chore_helper/chore.py", line 355, in chore_schedule
    yield datetime.strptime(add_date_str, "%Y-%m-%d").date()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y-%m-%d'
```

### Diagnostics dump

dl fails

**Comment by sandwichdreams** [comment]
Same problem for me. Do we have any updates on this?
 
- If I edit a chore, confirm, and then update the entity, it becomes unavailable.
- If I edit a chore, confirm, and close the editor in the pop-up, it becomes unavailable.

“This entity is no longer provided by the chore_helper integration. If the entity is no longer used, you can delete it in the settings.”
In other words, regardless of how I edit a task, the entity seems to become unavailable.
